[book]
authors = ["dDostalker"]
language = "cn"
description = "CTF中常见的python逆向入门教程"
multilingual = false
src = "src"
title = "CTFPython逆向入门"
github_repo = "https://github.com/CTFPyReBook/CTFPyReBook"

[output.html]
git-repository-url = "https://github.com/CTFPyReBook/CTFPyReBook"
git-repository-icon = "fa-github"
